// abapgit-pack: create abapGit-compatible ZIP from ABAP source files
//
// Usage:
//   abapgit-pack -dir ./src -mask "*.abap" -package $TMP -o output.zip
//   abapgit-pack -file program.abap -name ZPROG -desc "My program" -package $TMP -o output.zip
package main

import (
	"archive/zip"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	dir := flag.String("dir", "", "Directory with .abap files")
	file := flag.String("file", "", "Single .abap file")
	mask := flag.String("mask", "*.abap", "File mask for directory mode")
	name := flag.String("name", "", "Object name (auto-detected from filename if empty)")
	desc := flag.String("desc", "Generated by llvm2abap", "Description")
	pkg := flag.String("package", "$TMP", "SAP package")
	output := flag.String("o", "output.zip", "Output ZIP file")
	flag.Parse()

	if *file == "" && *dir == "" {
		fmt.Fprintln(os.Stderr, "Usage: abapgit-pack -file prog.abap -package $TMP -o out.zip")
		fmt.Fprintln(os.Stderr, "   or: abapgit-pack -dir ./src -mask '*.abap' -package $TMP -o out.zip")
		os.Exit(1)
	}

	type entry struct {
		name   string // ZPROG
		source string // REPORT source
		desc   string
	}

	var entries []entry

	if *file != "" {
		src, err := os.ReadFile(*file)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error reading %s: %v\n", *file, err)
			os.Exit(1)
		}
		objName := *name
		if objName == "" {
			// Auto-detect from REPORT statement or filename
			base := filepath.Base(*file)
			objName = strings.TrimSuffix(base, filepath.Ext(base))
			objName = strings.ToUpper(objName)
		}
		entries = append(entries, entry{name: objName, source: string(src), desc: *desc})
	}

	if *dir != "" {
		matches, err := filepath.Glob(filepath.Join(*dir, *mask))
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error globbing: %v\n", err)
			os.Exit(1)
		}
		for _, f := range matches {
			src, err := os.ReadFile(f)
			if err != nil {
				continue
			}
			base := filepath.Base(f)
			objName := strings.TrimSuffix(base, filepath.Ext(base))
			objName = strings.ToUpper(objName)
			entries = append(entries, entry{name: objName, source: string(src), desc: *desc})
		}
	}

	if len(entries) == 0 {
		fmt.Fprintln(os.Stderr, "No files found")
		os.Exit(1)
	}

	// Create ZIP
	f, err := os.Create(*output)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating %s: %v\n", *output, err)
		os.Exit(1)
	}
	defer f.Close()

	w := zip.NewWriter(f)

	// Add .abapgit.xml (repo metadata)
	addFile(w, ".abapgit.xml", fmt.Sprintf(`<?xml version="1.0" encoding="utf-8"?>
<asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">
 <asx:values>
  <DATA>
   <MASTER_LANGUAGE>E</MASTER_LANGUAGE>
   <STARTING_FOLDER>/src/</STARTING_FOLDER>
   <FOLDER_LOGIC>PREFIX</FOLDER_LOGIC>
   <IGNORE>
    <item>/.gitignore</item>
    <item>/LICENSE</item>
    <item>/README.md</item>
   </IGNORE>
  </DATA>
 </asx:values>
</asx:abap>
`))

	// Add package devc
	lower := strings.ToLower(strings.TrimPrefix(*pkg, "$"))
	addFile(w, fmt.Sprintf("src/%s.devc.xml", lower), fmt.Sprintf(`<?xml version="1.0" encoding="utf-8"?>
<abapGit version="v1.0.0" serializer="LCL_OBJECT_DEVC" serializer_version="v1.0.0">
 <asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">
  <asx:values>
   <DEVC>
    <CTEXT>%s</CTEXT>
   </DEVC>
  </asx:values>
 </asx:abap>
</abapGit>
`, *desc))

	for _, e := range entries {
		lowerName := strings.ToLower(e.name)

		// Source file
		addFile(w, fmt.Sprintf("src/%s.prog.abap", lowerName), e.source)

		// XML metadata
		descLen := len(e.desc)
		if descLen > 70 {
			descLen = 70
		}
		addFile(w, fmt.Sprintf("src/%s.prog.xml", lowerName), fmt.Sprintf(`<?xml version="1.0" encoding="utf-8"?>
<abapGit version="v1.0.0" serializer="LCL_OBJECT_PROG" serializer_version="v1.0.0">
 <asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">
  <asx:values>
   <PROGDIR>
    <NAME>%s</NAME>
    <SUBC>1</SUBC>
    <RSTAT>K</RSTAT>
    <FIXPT>X</FIXPT>
    <UCCHECK>X</UCCHECK>
   </PROGDIR>
   <TPOOL>
    <item>
     <ID>R</ID>
     <ENTRY>%s</ENTRY>
     <LENGTH>%d</LENGTH>
    </item>
   </TPOOL>
  </asx:values>
 </asx:abap>
</abapGit>
`, e.name, e.desc, descLen))

		fmt.Fprintf(os.Stderr, "Added: %s (%d bytes)\n", e.name, len(e.source))
	}

	w.Close()
	fmt.Printf("Created %s with %d objects\n", *output, len(entries))
}

func addFile(w *zip.Writer, name, content string) {
	f, _ := w.Create(name)
	f.Write([]byte(content))
}
